remote_theme: mmistakes/minimal-mistakes
title: Welcome 
include: ["_pages"]

author:
  name: "Natalia F.B"
  avatar: "https://pm1.narvii.com/6269/05e019be43474f4dbb491bd336db3aa228d19ec8_hq.jpg"
  bio: "Future Techie"
