remote_theme: mmistakes/minimal-mistakes
title: All About Natalia 
include: ["_pages"]

author:
  name: "Natalia F.B"
  avatar: "https://i.pinimg.com/736x/17/4b/1d/174b1de529956bb90a7885b05b95de99--sweet-drawings-girl-drawings.jpg"
  bio: "Just a human being"
