remote_theme: mmistakes/minimal-mistakes
title: Galaxy NGC 891
include: ["_pages"]

author:
  name: "Jane Doe"
  avatar: "https://i.pinimg.com/736x/17/4b/1d/174b1de529956bb90a7885b05b95de99--sweet-drawings-girl-drawings.jpg"
  bio: "Just an average person"
