remote_theme: mmistakes/minimal-mistakes
title: Welcome! 
include: ["_pages"]

author:
  name: "Natalia Figueroa-Bernal"
  avatar: "https://68.media.tumblr.com/5c324c3db0c776106f74fbeba67c2f1c/tumblr_ohzew4ODUj1rkcev7o1_400.gif"
  bio: "Future Techie"
