remote_theme: mmistakes/minimal-mistakes
title: Welcome! 
include: ["_pages"]

author:
  name: "Natalia F.B"
  avatar: "https://images.search.yahoo.com/search/images;_ylt=AwrBT6JUiHZaOAMALR5XNyoA;_ylu=X3oDMTEyNG84YmdiBGNvbG8DYmYxBHBvcwMxBHZ0aWQDQjQ5ODJfMQRzZWMDc2M-?p=profile+pic&fr=mcafee&th=122.6&tw=122.6&imgurl=http%3A%2F%2Fwww.eurogeosurveys.org%2Fwp-content%2Fuploads%2F2014%2F02%2Fdefault_profile_pic.jpg&rurl=http%3A%2F%2Fwww.eurogeosurveys.org%2Fabout-us%2Forganisation%2F&size=17KB&name=Organisation+-+www.eurogeosurveys.org&oid=2&h=600&w=600&turl=http%3A%2F%2Fts4.mm.bing.net%2Fth%3Fid%3DOIP.1LRUIB2OXVePxD5hQm4fqwHaHa%26pid%3D15.1%26rs%3D1%26c%3D1%26qlt%3D95%26w%3D122%26h%3D122&tt=Organisation+-+www.eurogeosurveys.org&sigr=11kpbn27p&sigit=130l904jl&sigi=129qloj7q&sign=115lmks6r&sigt=115lmks6r"
  bio: "Future Techie"
