remote_theme: mmistakes/minimal-mistakes
title: All About Natalia 
include: ["_pages"]

author:
  name: "Natalia F.B"
  avatar: "https://www.facebook.com/photo.php?fbid=1192253010907452&l=da14954cb0"
  bio: "Just a human being"
